---
title: "Public Health Data Exchange (PHDX)"
format:
  html:
    code-tools: 
      source: /load.qmd 
server: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(shiny)
library(tidyverse)
library(scales)
library(janitor)
```

```{r, echo=F}
"%!in%" <- function(x,y)!("%in%"(x,y))

# Interactive
df1 <- read_csv('./Data/Harmonized Opioid Overdose Datasets_01.23.2025.csv', show_col_types = FALSE) |>
  clean_names() |> 
  dplyr::filter(!(count %in% c(7777, 8888, 9999))) |> 
  dplyr::filter(!(crude_rate %in% c(7777, 8888, 9999))) |> 
  dplyr::filter(!(age_adjusted_rate %in% c(7777, 8888, 9999))) %>%
  mutate(qtr=as.numeric((gsub("Q",'', quarter))), 
         qtr =if_else(is.na(qtr),1,qtr),
         qdate= year+ qtr/4 -1/4
         )

```

## PHDX

Welcome to the Public Health Data Exchange, hosted by the Yale School of Public Health. Here you can find visualizations of diverse datasets related to public health outcomes of general interest.

## Opioids in the United States

```{r}
#| panel: sidebar

selectInput("state.select", "State:", 
            choices=unique(df1$state), selected='US')
```

::: panel-tabset
### Trends in healthcare visits

```{r}
#| panel: fill
plotlyOutput("distPlot1")

```

```{r}
#| context: server

df1 <- read_csv('./Data/Harmonized Opioid Overdose Datasets_01.23.2025.csv', show_col_types = FALSE) |>
  clean_names() |> 
  dplyr::filter(!(count %in% c(7777, 8888, 9999))) |> 
  dplyr::filter(!(crude_rate %in% c(7777, 8888, 9999))) |> 
  dplyr::filter(!(age_adjusted_rate %in% c(7777, 8888, 9999))) %>%
  mutate(qtr=as.numeric((gsub("Q",'', quarter))), 
         qtr =if_else(is.na(qtr),1,qtr),
         qdate= year+ qtr/4 -1/4
         )

output$distPlot1 <- renderPlotly({
  
 p1 <- df1 %>%
    dplyr::filter(drug=='All Opioids' & characteristic=='Age' & dataset=='AHRQ' & state == input$state.select ) %>%
    group_by(qdate, level) %>%
    summarize(count=sum(count)) %>% #combine outpatient nad inpatient
  ggplot(aes(x=qdate, y=count, group=level, color=level)) +
    theme_minimal() +
    geom_line()
p1
})

output$distPlot2 <- renderPlotly({
  
 p1 <- df1 %>%
    dplyr::filter(drug=='All Opioids' & characteristic=='Age' & dataset=='NCHS' & state == input$state.select ) %>%
    group_by(qdate, level) %>%
    summarize(count=sum(count)) %>% #combine outpatient nad inpatient
  ggplot(aes(x=qdate, y=count, group=level, color=level)) +
    theme_minimal() +
    geom_line()
p1
})
```

### Trends in deaths

:::

------------------------------------------------------------------------

## RSV in the United States

```{r}
#| panel: sidebar

selectInput("state.select", "State:", 
            choices=unique(df1$state), selected='US')
```

::: panel-tabset

### Trends in hospitalizations
```{r}
#| panel: fill

```

### Trends in positive tests
```{r}
#| panel: fill

```

### Trends in Google searches
```{r}
#| panel: fill

```

:::


## Explanation and Context

The above visualizations provide a blend of temporal and spatial insights:

-   **Time Series Plots**: Observe trends and fluctuations over time.
-   **Maps**: Geographical context enriches understanding, linking data to place.

------------------------------------------------------------------------
